name: CanID

channels:
    - conda-forge
    - bioconda
    - nodefaults

dependencies:
    - r-base=4.3.1
    - bioconductor-sva
    - bioconductor-limma
    - python=3.10.4
    - pandas=2.0.1
    - numpy=1.22.3
    - qnorm=0.8.1
    - scikit-learn=1.1.1
    - scipy=1.8.0
    - matplotlib
    - nextflow
